// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/password.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPasswordChecker is a mock of PasswordChecker interface.
type MockPasswordChecker struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordCheckerMockRecorder
}

// MockPasswordCheckerMockRecorder is the mock recorder for MockPasswordChecker.
type MockPasswordCheckerMockRecorder struct {
	mock *MockPasswordChecker
}

// NewMockPasswordChecker creates a new mock instance.
func NewMockPasswordChecker(ctrl *gomock.Controller) *MockPasswordChecker {
	mock := &MockPasswordChecker{ctrl: ctrl}
	mock.recorder = &MockPasswordCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordChecker) EXPECT() *MockPasswordCheckerMockRecorder {
	return m.recorder
}

// CheckPassword mocks base method.
func (m *MockPasswordChecker) CheckPassword(hashedPassword, plainPassword string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPassword", hashedPassword, plainPassword)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckPassword indicates an expected call of CheckPassword.
func (mr *MockPasswordCheckerMockRecorder) CheckPassword(hashedPassword, plainPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPassword", reflect.TypeOf((*MockPasswordChecker)(nil).CheckPassword), hashedPassword, plainPassword)
}

// MockPasswordHasher is a mock of PasswordHasher interface.
type MockPasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordHasherMockRecorder
}

// MockPasswordHasherMockRecorder is the mock recorder for MockPasswordHasher.
type MockPasswordHasherMockRecorder struct {
	mock *MockPasswordHasher
}

// NewMockPasswordHasher creates a new mock instance.
func NewMockPasswordHasher(ctrl *gomock.Controller) *MockPasswordHasher {
	mock := &MockPasswordHasher{ctrl: ctrl}
	mock.recorder = &MockPasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordHasher) EXPECT() *MockPasswordHasherMockRecorder {
	return m.recorder
}

// HashPassword mocks base method.
func (m *MockPasswordHasher) HashPassword(plainPassword string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", plainPassword)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockPasswordHasherMockRecorder) HashPassword(plainPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockPasswordHasher)(nil).HashPassword), plainPassword)
}
