// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/job_grades_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/erinchen11/hr-system/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockJobGradeService is a mock of JobGradeService interface.
type MockJobGradeService struct {
	ctrl     *gomock.Controller
	recorder *MockJobGradeServiceMockRecorder
}

// MockJobGradeServiceMockRecorder is the mock recorder for MockJobGradeService.
type MockJobGradeServiceMockRecorder struct {
	mock *MockJobGradeService
}

// NewMockJobGradeService creates a new mock instance.
func NewMockJobGradeService(ctrl *gomock.Controller) *MockJobGradeService {
	mock := &MockJobGradeService{ctrl: ctrl}
	mock.recorder = &MockJobGradeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobGradeService) EXPECT() *MockJobGradeServiceMockRecorder {
	return m.recorder
}

// CreateJobGrade mocks base method.
func (m *MockJobGradeService) CreateJobGrade(ctx context.Context, jobGrade *models.JobGrade) (*models.JobGrade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJobGrade", ctx, jobGrade)
	ret0, _ := ret[0].(*models.JobGrade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJobGrade indicates an expected call of CreateJobGrade.
func (mr *MockJobGradeServiceMockRecorder) CreateJobGrade(ctx, jobGrade interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJobGrade", reflect.TypeOf((*MockJobGradeService)(nil).CreateJobGrade), ctx, jobGrade)
}

// DeleteJobGrade mocks base method.
func (m *MockJobGradeService) DeleteJobGrade(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJobGrade", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJobGrade indicates an expected call of DeleteJobGrade.
func (mr *MockJobGradeServiceMockRecorder) DeleteJobGrade(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobGrade", reflect.TypeOf((*MockJobGradeService)(nil).DeleteJobGrade), ctx, id)
}

// GetJobGradeByCode mocks base method.
func (m *MockJobGradeService) GetJobGradeByCode(ctx context.Context, code string) (*models.JobGrade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobGradeByCode", ctx, code)
	ret0, _ := ret[0].(*models.JobGrade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobGradeByCode indicates an expected call of GetJobGradeByCode.
func (mr *MockJobGradeServiceMockRecorder) GetJobGradeByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobGradeByCode", reflect.TypeOf((*MockJobGradeService)(nil).GetJobGradeByCode), ctx, code)
}

// GetJobGradeByID mocks base method.
func (m *MockJobGradeService) GetJobGradeByID(ctx context.Context, id uuid.UUID) (*models.JobGrade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobGradeByID", ctx, id)
	ret0, _ := ret[0].(*models.JobGrade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobGradeByID indicates an expected call of GetJobGradeByID.
func (mr *MockJobGradeServiceMockRecorder) GetJobGradeByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobGradeByID", reflect.TypeOf((*MockJobGradeService)(nil).GetJobGradeByID), ctx, id)
}

// ListJobGrades mocks base method.
func (m *MockJobGradeService) ListJobGrades(ctx context.Context) ([]models.JobGrade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobGrades", ctx)
	ret0, _ := ret[0].([]models.JobGrade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobGrades indicates an expected call of ListJobGrades.
func (mr *MockJobGradeServiceMockRecorder) ListJobGrades(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobGrades", reflect.TypeOf((*MockJobGradeService)(nil).ListJobGrades), ctx)
}

// UpdateJobGrade mocks base method.
func (m *MockJobGradeService) UpdateJobGrade(ctx context.Context, id uuid.UUID, updates *models.JobGrade) (*models.JobGrade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobGrade", ctx, id, updates)
	ret0, _ := ret[0].(*models.JobGrade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateJobGrade indicates an expected call of UpdateJobGrade.
func (mr *MockJobGradeServiceMockRecorder) UpdateJobGrade(ctx, id, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobGrade", reflect.TypeOf((*MockJobGradeService)(nil).UpdateJobGrade), ctx, id, updates)
}
